# The RAGFlow team do not actively maintain docker-compose-gpu.yml, so use them at your own risk. 
# Pull requests to improve it are welcome.
include:
  - ./docker-compose-base.yml

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 19530:80
      - 55443:443
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../history_data_agent:/ragflow/history_data_agent
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./entrypoint.sh:/ragflow/entrypoint.sh
      - ../conf:/ragflow/conf

    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      # - KM_RSA_PRIVATE_KEY_PATH=/app/api/config/km_private_key.pem
      - PUBLIC_API_TOKEN=dbbV1cU0i5ZIcCMjMi-q3JVveyKm90G2rXz7O6WrdHBuszNdfTZ78NtWCmdWh8zneXGn36HAWa2752eg1kOMNwbw1tu1onqMLiDJL7mvuTnlFPezqrhBT_c49ukJ973QLw1ubgDpSmVuAgaV2S-SNcT1pVJNeRfzeDhivMGolS6ke_qCXTqRrX7twfVYrcntSuqaDqIyPgj1SxGUbcX1XloVCHh7_2jxB6jxBC3LyrG-6ALg62UE91yFKy63YkYgreKqB8OdqO0baD8YgnLX119TfQlMko0-m2jIU8mrlL5NHC3V7vs1pZ4BKoipEOgD1UaXxMv8QGigxA-1EDx-ag==
    networks:
      - ragflow
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"

#    deploy: 
#     resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
